inherit_from: .rubocop_todo.yml

Style/FileName:
  Exclude:
    - 'lib/vagrant-vsphere.rb'

Lint/RescueException:
  Exclude:

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
